[package]
name = "bp-core"
version = "0.8.0"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Bitcoin Protocol Core Library (BP Core Lib)"
repository = "https://github.com/LNP-BP/bp-core"
homepage = "https://github.com/LNP-BP"
keywords = ["lnp-bp", "cryptocurrency", "smart-contracts", "bitcoin"]
categories = ["cryptography::cryptocurrencies", "encoding", "parsing"]
readme = "README.md"
edition = "2021"
rust-version = "1.59.0"
exclude = [".github", "dbc", "seals", "dbc-legacy", "seals-legacy"]

[lib]
name = "bp"
path = "src/lib.rs"

[[bin]]
name = "dbc"
required-features = ["cli", "serde"]

[[bin]]
name = "seals"
required-features = ["cli", "serde"]

[dependencies]
amplify = "3.13.0"
strict_encoding = "0.8.1"
commit_verify = "0.8.0"
single_use_seals = "0.8.0"
bitcoin = "0.28.1"
psbt = { git = "https://github.com/zoedberg/descriptor-wallet", branch = "fixes", version = "0.8.0", optional = true }
bp-dbc = { version = "0.8.0", path = "./dbc" }
bp-seals = { version = "0.8.0", path = "./seals" }
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }
serde_with = { version = "1.8", optional = true }
electrum-client = { version = "0.11.0", optional = true }
clap = { version = "~3.1.18", optional = true, features = ["derive"] }
colored = { version = "2", optional = true }

[features]
default = []
all = ["async", "serde", "miniscript", "cli", "wallet"]
cli = ["clap", "colored", "electrum-client", "miniscript", "wallet"]
wallet = ["psbt", "bp-dbc/wallet"]
miniscript = ["bp-dbc/miniscript", "bp-seals/miniscript"]
async = ["bp-seals/async"]
serde = ["amplify/serde", "bitcoin/use-serde",
         "commit_verify/serde", "bp-dbc/serde", "bp-seals/serde",
         "serde_crate", "serde_with"]

[workspace]
members = [".", "dbc", "seals"]
default-members = [".", "dbc", "seals"]
exclude = ["seals-legacy", "dbc-legacy"]
