[package]
name = "bp-dbc"
version = "0.8.0"
license = "Apache-2.0"
authors = ["Dr. Maxim Orlovsky <orlovsky@pandoracore.com>"]
description = "Deterministic bitcoin commitments library"
repository = "https://github.com/LNP-BP/bp-core"
homepage = "https://github.com/LNP-BP"
keywords = ["lnp-bp", "bitcoin", "cryptography", "smart-contracts", "single-use-seals"]
categories = ["cryptography::cryptocurrencies", "encoding"]
readme = "../README.md"
edition = "2021"
rust-version = "1.59.0"

[lib]
name = "dbc"
path = "src/lib.rs"

[dependencies]
amplify = "3.13.0"
bitcoin = "0.28.1"
secp256k1 = { version = "0.22.1", features = ["global-context", "rand-std"] }
bitcoin_scripts = "0.8.0"
descriptors = { version = "0.8.0", optional = true }
psbt = { git = "https://github.com/zoedberg/descriptor-wallet", branch = "fixes", version = "0.8.4", default-features = false, optional = true }
strict_encoding = "0.8.1"
commit_verify = { version = "0.8.0", features = ["rand"] }
miniscript_crate = { package = "miniscript", version = "7.0.0", optional = true }
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }
serde_with = { version = "1.8", optional = true }

[features]
default = []
all = ["serde", "miniscript", "wallet"]
wallet = ["psbt"]
miniscript = ["miniscript_crate", "bitcoin_scripts/miniscript", "psbt/miniscript", "descriptors"]
serde = ["amplify/serde", "bitcoin/use-serde", "bitcoin_scripts/serde", "commit_verify/serde", "serde_crate", "serde_with"]
